[project]
name = "netbox-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dan Trickey", email = "git@trickey.io" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
netbox-scripts = "netbox_scripts:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "prek>=0.5.5",
    "ruff>=0.16.10",
]
